### ISSUE TITLE
Point out that Chrome's “This site has been updated in the background” notification only show up in Windows

### ISSUE THREAD

**Issue by kenrick95** [gauntface/web-push-book#90]
Point out that Chrome's “This site has been updated in the background” notification only show up in Windows

cc @gauntface

## Type of Issue
Add more info to [this book section](https://web-push-book.gauntface.com/chapter-07/01-faq/#why-do-i-get-the-this-site-has-been-updated-in-the-background)

## Details....
Because I observed that this behavior is not present at latest Chrome on Mac. (Maybe it used to be the case before Chrome on Mac switch to user MacOS's Notification Center?)

**Comment by gauntface** [comment]
It's difficult to explain but it is present on all platforms.

It may not appear because there is a budget behind the scenes which will be reduced each time you send a push and show no notification as long as the page isn't currently open and focused. The reason I don't discuss this is because a developer cannot tell what the budget is, whether it's going down or not and ultimately it could change in the future. But the notification is there on every platform.
